spring.datasource:
  hikari.maximum-pool-size: 20
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: postgres
  driver-class-name: org.postgresql.Driver

spring.jpa:
  database: postgresql
  hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  hibernate.ddl-auto: create-drop
  propeties.hibernate.format_sql: true
  show-sql: true
  open-in-view: false

jwt:
  secret-key: simple_sungsu_sns_202310_secret_key
  # 30 days
  token.expired-time-ms: 2592000000